name: Nix Flake Check

on:
  pull_request:
  push:

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: nicolas-guichard
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check -L --accept-flake-config '.?submodules=1#' --override-input self-with-dotgit path:$(pwd)
